import { useEffect, useState } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import api, { ApiError } from '../lib/api'
import { ApiNotice, Spinner } from '../components/AuthLayout'
import { formatDate, formatMoney } from '../lib/format'
import type { DefaultedResponse } from '../types/reports'

export default function CapitalLossPage() {
  const [params, setParams] = useSearchParams(); const [from, setFrom] = useState(params.get('from') || ''); const [to, setTo] = useState(params.get('to') || ''); const [result, setResult] = useState<DefaultedResponse | null>(null); const [loading, setLoading] = useState(true); const [notice, setNotice] = useState('')
  const query = new URLSearchParams({ ...(from ? { from } : {}), ...(to ? { to } : {}) }).toString()
  useEffect(() => { api.get<DefaultedResponse>(`/reports/defaulted${query ? `?${query}` : ''}`).then(({ data }) => setResult(data)).catch((error: ApiError) => setNotice(error.message)).finally(() => setLoading(false)) }, [query])
  return <section className="page-frame"><div className="page-heading"><div><span className="eyebrow">Reports / Owner only</span><h1>Capital loss</h1><p className="page-intro">Defaulted loans and the principal that could not be recovered.</p></div><div className="loss-figure"><span className="eyebrow">Total capital loss</span><strong>{formatMoney(result?.total_capital_loss)}</strong></div></div><form className="report-filters" onSubmit={(event) => { event.preventDefault(); setParams({ ...(from ? { from } : {}), ...(to ? { to } : {}) }) }}><label>From<input type="date" value={from} onChange={(event) => setFrom(event.target.value)} /></label><label>To<input type="date" value={to} onChange={(event) => setTo(event.target.value)} /></label><button className="primary-button filter-button" type="submit">Apply filters <span>↗</span></button></form><ApiNotice message={notice} />{loading ? <div className="state-block"><Spinner /><p>Loading capital loss...</p></div> : result && result.loans.length === 0 ? <div className="state-block empty-state"><h2>No defaults recorded.</h2><p>This date range has no capital loss to report.</p></div> : result && <div className="report-table-wrap"><table className="data-table"><thead><tr><th>Loan</th><th>Customer</th><th>Principal</th><th>Recovered</th><th>Capital loss</th><th>Defaulted</th><th>Reason</th></tr></thead><tbody>{result.loans.map((loan) => <tr key={loan.loan_display_code}><td className="display-code">{loan.loan_display_code}</td><td>{loan.customer_id ? <Link className="table-link" to={`/customers/${loan.customer_id}`}>{loan.customer_name}</Link> : loan.customer_name}</td><td>{formatMoney(loan.principal)}</td><td>{formatMoney(loan.total_paid_before_default)}</td><td className="loss-value">{formatMoney(loan.capital_loss)}</td><td>{formatDate(loan.defaulted_at)}</td><td>{loan.default_reason || '—'}</td></tr>)}</tbody></table></div>}</section>
}