import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import api, { ApiError } from '../lib/api'
import { ApiNotice, Field, Spinner } from '../components/AuthLayout'
import { getFieldError } from '../components/formUtils'
import LocationPicker from '../components/LocationPicker'
import type { Customer, Pagination } from '../types/data'

const emptyCustomer = { name: '', phone: '', address: '', latitude: '', longitude: '' }

export default function CustomersPage() {
  const [customers, setCustomers] = useState<Customer[]>([]); const [pagination, setPagination] = useState<Pagination>({ page: 1, limit: 10, total: 0 }); const [search, setSearch] = useState(''); const [query, setQuery] = useState(''); const [refreshKey, setRefreshKey] = useState(0); const [loading, setLoading] = useState(true); const [modalOpen, setModalOpen] = useState(false); const [saving, setSaving] = useState(false); const [notice, setNotice] = useState(''); const [errors, setErrors] = useState<Record<string, string[] | string>>({}); const [form, setForm] = useState(emptyCustomer); const [coordinates, setCoordinates] = useState<{ latitude?: number; longitude?: number }>({})

  useEffect(() => { const timer = window.setTimeout(() => { setQuery(search); setPagination((value) => ({ ...value, page: 1 })) }, 350); return () => window.clearTimeout(timer) }, [search])
  useEffect(() => { let active = true; const timer = window.setTimeout(() => { setLoading(true); api.get<{ customers: Customer[]; pagination: Pagination }>('/customers', { params: { search: query, page: pagination.page, limit: pagination.limit } }).then(({ data }) => { if (active) { setCustomers(data.customers); setPagination(data.pagination) } }).catch((error: ApiError) => { if (active) setNotice(error.message) }).finally(() => { if (active) setLoading(false) }) }, 0); return () => { active = false; window.clearTimeout(timer) } }, [query, pagination.page, pagination.limit, refreshKey])

  const update = (key: keyof typeof emptyCustomer, value: string) => setForm((current) => ({ ...current, [key]: value }))
  const create = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); setNotice(''); setErrors({}); try { await api.post('/customers', { ...form, latitude: coordinates.latitude, longitude: coordinates.longitude }); setModalOpen(false); setForm(emptyCustomer); setCoordinates({}); setPagination((value) => ({ ...value, page: 1 })); setRefreshKey((value) => value + 1) } catch (error) { const value = error as ApiError; setErrors(value.fieldErrors ?? {}); setNotice(value.message) } finally { setSaving(false) } }
  const pageCount = Math.max(1, Math.ceil(pagination.total / pagination.limit))

  return <section className="page-frame"><div className="page-heading"><div><span className="eyebrow">Directory / {pagination.total} records</span><h1>Customers</h1><p className="page-intro">The people and places at the heart of your collection route.</p></div><button className="primary-button add-button" type="button" onClick={() => { setModalOpen(true); setNotice(''); setErrors({}); setCoordinates({}) }}>Add customer <span aria-hidden="true">+</span></button></div><div className="toolbar"><label className="search-field"><span>Search customers</span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Name, phone, or code" /></label><span className="toolbar-note">{query ? `Results for “${query}”` : 'All customers'}</span></div><ApiNotice message={notice} />{loading ? <div className="state-block"><Spinner /><p>Loading customers...</p></div> : customers.length === 0 ? <div className="state-block empty-state"><span className="placeholder-number">00</span><h2>{query ? 'No matches found.' : 'No customers yet.'}</h2><p>{query ? 'Try another name, phone number, or display code.' : 'Add your first customer to begin building the route.'}</p></div> : <><div className="customer-table-wrap"><table className="data-table"><thead><tr><th>Code</th><th>Name</th><th>Phone</th><th>Address</th><th /></tr></thead><tbody>{customers.map((customer) => <tr key={customer.id}><td><span className="display-code">{customer.display_code}</span></td><td><Link className="table-link" to={`/customers/${customer.id}`}>{customer.name}</Link></td><td>{customer.phone || '—'}</td><td>{customer.address || '—'}</td><td><Link className="row-arrow" to={`/customers/${customer.id}`} aria-label={`View ${customer.name}`}>↗</Link></td></tr>)}</tbody></table></div><div className="customer-cards">{customers.map((customer) => <Link className="customer-card" to={`/customers/${customer.id}`} key={customer.id}><div><span className="display-code">{customer.display_code}</span><h2>{customer.name}</h2><p>{customer.phone || 'No phone'} · {customer.address || 'No address'}</p></div><span>↗</span></Link>)}</div><div className="pagination"><button type="button" className="text-button" disabled={pagination.page <= 1} onClick={() => setPagination((value) => ({ ...value, page: value.page - 1 }))}>← Previous</button><span>Page {pagination.page} of {pageCount}</span><button type="button" className="text-button" disabled={pagination.page >= pageCount} onClick={() => setPagination((value) => ({ ...value, page: value.page + 1 }))}>Next →</button></div></>}
    {modalOpen && <div className="dialog-backdrop"><section className="dialog form-dialog"><div className="dialog-heading"><div><p className="eyebrow">New record</p><h2>Add customer</h2></div><button className="close-button" type="button" onClick={() => setModalOpen(false)} aria-label="Close">×</button></div><form className="data-form" onSubmit={create} noValidate><div className="form-grid"><Field label="Name" error={getFieldError(errors, 'name')}><input value={form.name} onChange={(event) => update('name', event.target.value)} autoComplete="name" /></Field><Field label="Phone" error={getFieldError(errors, 'phone')}><input value={form.phone} onChange={(event) => update('phone', event.target.value)} inputMode="tel" autoComplete="tel" /></Field></div><Field label="Address" error={getFieldError(errors, 'address')}><input value={form.address} onChange={(event) => update('address', event.target.value)} autoComplete="street-address" /></Field><div><p className="location-label">Location</p><LocationPicker onChange={(latitude, longitude) => setCoordinates({ latitude, longitude })} /></div><ApiNotice message={notice} /><button className="primary-button" type="submit" disabled={saving}>{saving ? <Spinner /> : 'Save customer'}<span aria-hidden="true">↗</span></button></form></section></div>}
  </section>
}