import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import api, { ApiError } from '../lib/api'
import { ApiNotice, Spinner } from '../components/AuthLayout'
import ConfirmDialog from '../components/ConfirmDialog'
import { formatMoney } from '../lib/format'
import { useLanguage } from '../hooks/useLanguageHook'
import type { DailyDueEntry, DailyDueResponse } from '../types/reports'

const today = () => new Date().toLocaleDateString('en-CA')
export default function DailyReportPage() {
  const { t } = useLanguage(); const [date, setDate] = useState(today); const [result, setResult] = useState<DailyDueResponse | null>(null); const [loading, setLoading] = useState(true); const [notice, setNotice] = useState(''); const [collecting, setCollecting] = useState<DailyDueEntry | null>(null); const [saving, setSaving] = useState(false)
  useEffect(() => { api.get<DailyDueResponse>(`/reports/daily-due?date=${date}`).then(({ data }) => setResult(data)).catch((error: ApiError) => setNotice(error.message)).finally(() => setLoading(false)) }, [date])
  const quickPay = async () => { if (!collecting) return; setSaving(true); setNotice(''); try { const paidAt = new Date(`${date}T00:00:00.000Z`).toISOString(); const body = collecting.loan_type === 'daily' ? { amount: collecting.amount_due, paid_at: paidAt } : { normal_cycle_amount: collecting.amount_due, paid_at: paidAt }; await api.post(`/loans/${collecting.loan_id}/payments`, body); setResult((current) => current ? { ...current, total_collected: current.total_collected + collecting.amount_due, entries: current.entries.map((entry) => entry.loan_id === collecting.loan_id ? { ...entry, is_paid: true } : entry) } : current); setCollecting(null) } catch (error) { setNotice((error as ApiError).message) } finally { setSaving(false) } }
  const entries = result?.entries || []; const unpaid = entries.filter((entry) => !entry.is_paid); const paid = entries.filter((entry) => entry.is_paid); const row = (entry: DailyDueEntry) => <div className="daily-report-row" key={entry.loan_id}><Link className="report-person" to={`/customers/${entry.customer_id}`}><strong>{entry.customer_name}</strong><small>{entry.customer_display_code || entry.loan_display_code}</small></Link><span className="loan-type-badge">{entry.loan_type === 'daily' ? t('common.daily') : t('common.monthly')}</span><strong>{formatMoney(entry.amount_due)}</strong>{entry.is_paid ? <span className="payment-status paid">✓ {t('common.paid')}</span> : <button className="primary-button quick-pay-button" type="button" onClick={() => setCollecting(entry)}>{t('common.collect')}</button>}<Link className="row-arrow" to={`/loans/${entry.loan_id}`} aria-label={t('common.loan')}>↗</Link></div>
  const changeDate = (value: string) => { setLoading(true); setDate(value) }
  return <section className="page-frame report-page"><div className="page-heading"><div><span className="eyebrow">{t('nav.dailyReport')}</span><h1>{t('reports.dailyTitle')}</h1><p className="page-intro">{t('reports.dailyIntro')}</p></div><label className="large-date-picker">{t('reports.chooseDate')}<input type="date" value={date} onChange={(event) => changeDate(event.target.value)} /></label></div><ApiNotice message={notice} />{loading ? <div className="state-block"><Spinner /><p>{t('common.loading')}</p></div> : result && <><p className="daily-summary">{formatMoney(result.total_due)} {t('reports.toCollect')}, {formatMoney(result.total_collected)} {t('reports.collectedToday')}</p>{entries.length === 0 ? <div className="state-block empty-state"><p>{t('reports.nothingDue')}</p></div> : <div className="daily-report-list">{unpaid.length > 0 && <><h2>{t('common.unpaid')}</h2>{unpaid.map(row)}</>}{paid.length > 0 && <><h2>{t('common.paid')}</h2>{paid.map(row)}</>}</div>}</>}{collecting && <ConfirmDialog title={t('reports.collectConfirm', { amount: formatMoney(collecting.amount_due), name: collecting.customer_name })} body={t('reports.collectConfirm', { amount: formatMoney(collecting.amount_due), name: collecting.customer_name })} confirmLabel={t('common.yes')} onCancel={() => setCollecting(null)} onConfirm={quickPay} loading={saving} />}</section>
}