import { useEffect, useState } from 'react'
import type { FormEvent } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import api, { ApiError } from '../lib/api'
import { ApiNotice, AuthLayout, Field, Spinner } from '../components/AuthLayout'
import { getFieldError } from '../components/formUtils'

export default function ForgotPasswordPage() {
  const navigate = useNavigate(); const [step, setStep] = useState(1); const [phone, setPhone] = useState(''); const [otp, setOtp] = useState(''); const [resetToken, setResetToken] = useState(''); const [maskedName, setMaskedName] = useState(''); const [password, setPassword] = useState(''); const [confirm, setConfirm] = useState(''); const [loading, setLoading] = useState(false); const [cooldown, setCooldown] = useState(0); const [notice, setNotice] = useState(''); const [errors, setErrors] = useState<Record<string, string[] | string>>({}); const [done, setDone] = useState(false)
  const run = async (action: () => Promise<void>) => { setLoading(true); setNotice(''); setErrors({}); try { await action() } catch (error) { const apiError = error as ApiError; setErrors(apiError.fieldErrors ?? {}); setNotice(apiError.status === 429 ? 'Too many attempts. Please wait before trying again.' : apiError.message) } finally { setLoading(false) } }
  const check = (event: FormEvent) => { event.preventDefault(); void run(async () => { const { data } = await api.post<{ exists: boolean; maskedName?: string }>('/auth/forgot-password/check', { phone }); if (!data.exists) { setNotice('We could not verify that account. Please check the number and try again.'); return } setMaskedName(data.maskedName ?? 'this account'); setStep(1.5) }) }
  const sendResetOtp = () => void run(async () => { await api.post('/auth/forgot-password/send-otp', { phone }); setCooldown(30); setStep(2) })
  const confirmIdentity = () => sendResetOtp()
  const verify = (event: FormEvent) => { event.preventDefault(); void run(async () => { const { data } = await api.post<{ resetToken: string }>('/auth/forgot-password/verify-otp', { phone, otp }); setResetToken(data.resetToken); setStep(3) }) }
  const reset = (event: FormEvent) => { event.preventDefault(); if (password.length < 8 || password !== confirm) { const validationErrors: Record<string, string> = {}; if (password.length < 8) validationErrors.password = 'Use at least 8 characters.'; if (password !== confirm) validationErrors.confirmPassword = 'Passwords do not match.'; setErrors(validationErrors); return } void run(async () => { await api.post('/auth/forgot-password/reset', { phone, newPassword: password, confirmPassword: confirm, resetToken }); setDone(true) }) }
  useEffect(() => { if (!cooldown) return; const timer = window.setInterval(() => setCooldown((value) => Math.max(0, value - 1)), 1000); return () => window.clearInterval(timer) }, [cooldown])
  if (done) return <AuthLayout eyebrow="Password updated" title="You are back in control." intro="Your new password is ready. Sign in to continue."><div className="success-block"><span className="success-mark">✓</span><p>Password reset successfully.</p><button className="primary-button" type="button" onClick={() => navigate('/login')}>Go to login <span aria-hidden="true">↗</span></button></div></AuthLayout>
  return <AuthLayout eyebrow={`Reset access / 0${step === 1.5 ? 1 : step} of 03`} title="A fresh start, securely." intro="We will verify your number before letting you choose a new password.">
    {step === 1 && <form className="auth-form" onSubmit={check} noValidate><Field label="Mobile number" error={getFieldError(errors, 'phone')}><input value={phone} onChange={(event) => setPhone(event.target.value)} inputMode="tel" autoComplete="tel" /></Field><ApiNotice message={notice} /><button className="primary-button" disabled={loading} type="submit">{loading ? <Spinner /> : 'Continue'}<span aria-hidden="true">↗</span></button></form>}
    {step === 1.5 && <div className="confirm-block"><p className="confirm-question">Is this you?</p><strong>{maskedName}</strong><p>We found an account connected to that number.</p><ApiNotice message={notice} /><button className="primary-button" disabled={loading} type="button" onClick={confirmIdentity}>{loading ? <Spinner /> : 'Send verification code'}<span aria-hidden="true">↗</span></button><button className="text-button centered" type="button" onClick={() => { setStep(1); setMaskedName('') }}>That is not me</button></div>}
    {step === 2 && <form className="auth-form" onSubmit={verify} noValidate><Field label="Verification code" error={getFieldError(errors, 'otp')} hint="Enter the code sent to your phone. No code is auto-submitted."><input value={otp} onChange={(event) => setOtp(event.target.value.replace(/\D/g, '').slice(0, 6))} inputMode="numeric" autoComplete="one-time-code" maxLength={6} /><button type="button" className="text-button" disabled={cooldown > 0 || loading} onClick={sendResetOtp}>{cooldown > 0 ? `Resend in ${cooldown}s` : 'Resend code'}</button></Field><ApiNotice message={notice} /><button className="primary-button" disabled={loading} type="submit">{loading ? <Spinner /> : 'Verify code'}<span aria-hidden="true">↗</span></button></form>}
    {step === 3 && <form className="auth-form" onSubmit={reset} noValidate><Field label="New password" error={getFieldError(errors, 'password')}><input type="password" value={password} onChange={(event) => setPassword(event.target.value)} autoComplete="new-password" /></Field><Field label="Confirm new password" error={getFieldError(errors, 'confirmPassword')}><input type="password" value={confirm} onChange={(event) => setConfirm(event.target.value)} autoComplete="new-password" /></Field><ApiNotice message={notice} /><button className="primary-button" disabled={loading} type="submit">{loading ? <Spinner /> : 'Set new password'}<span aria-hidden="true">↗</span></button></form>}
    <p className="auth-switch"><Link to="/login">Back to login</Link></p>
  </AuthLayout>
}