import { useEffect, useState } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import api, { ApiError } from '../lib/api'
import { ApiNotice, Spinner } from '../components/AuthLayout'
import { formatDate, formatMoney } from '../lib/format'
import type { InterestPaymentsResponse } from '../types/reports'

function defaultRange() { const now = new Date(); return { from: new Date(now.getFullYear(), now.getMonth(), 1).toLocaleDateString('en-CA'), to: new Date(now.getFullYear(), now.getMonth() + 1, 0).toLocaleDateString('en-CA') } }
export default function InterestPaymentsPage() {
  const [searchParams, setSearchParams] = useSearchParams(); const defaults = defaultRange(); const [from, setFrom] = useState(searchParams.get('from') || defaults.from); const [to, setTo] = useState(searchParams.get('to') || defaults.to); const [loanType, setLoanType] = useState(searchParams.get('loan_type') || ''); const [page, setPage] = useState(Number(searchParams.get('page') || 1)); const [result, setResult] = useState<InterestPaymentsResponse | null>(null); const [loading, setLoading] = useState(true); const [exporting, setExporting] = useState(false); const [notice, setNotice] = useState('')
  const query = new URLSearchParams({ from, to, page: String(page), limit: '20', ...(loanType ? { loan_type: loanType } : {}) }).toString()
  useEffect(() => { api.get<InterestPaymentsResponse>(`/reports/interest-payments?${query}`).then(({ data }) => setResult(data)).catch((error: ApiError) => setNotice(error.message)).finally(() => setLoading(false)) }, [query])
  const applyFilters = (event: React.FormEvent) => { event.preventDefault(); setPage(1); setSearchParams({ from, to, ...(loanType ? { loan_type: loanType } : {}) }) }
  const exportCsv = async () => { setExporting(true); setNotice(''); try { const response = await api.get(`/reports/collections?${new URLSearchParams({ from, to, format: 'csv', ...(loanType ? { loan_type: loanType } : {}) })}`, { responseType: 'blob' }); const url = URL.createObjectURL(response.data); const anchor = document.createElement('a'); anchor.href = url; anchor.download = `warikalk-collections-${from}-to-${to}.csv`; anchor.click(); URL.revokeObjectURL(url) } catch (error) { setNotice((error as ApiError).message) } finally { setExporting(false) } }
  const totalPages = result?.pagination.total_pages || result?.pagination.pages || Math.ceil((result?.pagination.total || 0) / (result?.pagination.limit || 20))
  return <section className="page-frame"><div className="page-heading"><div><span className="eyebrow">Reports / Ledger</span><h1>Interest payments</h1><p className="page-intro">Trace every collection behind the profit cards, then export the same filtered window.</p></div><button className="secondary-button report-action" type="button" onClick={exportCsv} disabled={exporting}>{exporting ? <Spinner /> : 'Export CSV'}<span>↓</span></button></div><form className="report-filters" onSubmit={applyFilters}><label>From<input type="date" value={from} onChange={(event) => setFrom(event.target.value)} /></label><label>To<input type="date" value={to} onChange={(event) => setTo(event.target.value)} /></label><label>Loan type<select value={loanType} onChange={(event) => setLoanType(event.target.value)}><option value="">All loans</option><option value="daily">Daily</option><option value="monthly">Monthly</option></select></label><button className="primary-button filter-button" type="submit">Apply filters <span>↗</span></button></form><ApiNotice message={notice} />{loading ? <div className="state-block"><Spinner /><p>Loading payments...</p></div> : result && result.payments.length === 0 ? <div className="state-block empty-state"><h2>No payments in this window.</h2><p>Try a wider date range or another loan type.</p></div> : result && <><div className="report-table-wrap"><table className="data-table"><thead><tr><th>Date</th><th>Customer</th><th>Loan</th><th>Payment type</th><th>Amount</th><th>Collected by</th></tr></thead><tbody>{result.payments.map((payment, index) => <tr key={`${payment.paid_at}-${payment.loan_display_code}-${index}`}><td>{formatDate(payment.paid_at)}</td><td>{payment.customer_id ? <Link className="table-link" to={`/customers/${payment.customer_id}`}>{payment.customer_name || 'Customer'}<small className="display-code">{payment.customer_display_code}</small></Link> : <><strong>{payment.customer_name || 'Customer'}</strong><small className="display-code">{payment.customer_display_code}</small></>}</td><td><span className="display-code">{payment.loan_display_code || '—'}</span><span className="loan-type-badge">{payment.loan_type}</span></td><td>{payment.payment_type || 'Payment'}</td><td>{formatMoney(payment.amount)}</td><td>{payment.collected_by_name || '—'}</td></tr>)}</tbody></table></div><div className="pagination"><span>{result.pagination.total} payments</span><div><button className="text-button" disabled={page <= 1} onClick={() => setPage(page - 1)}>Previous</button> <button className="text-button" disabled={!totalPages || page >= totalPages} onClick={() => setPage(page + 1)}>Next</button></div></div></>}</section>
}