import { useCallback, useEffect, useState } from 'react'
import platformApi from '../lib/platformApi'
import { ApiError } from '../lib/api'
import { ApiNotice, Spinner } from '../components/AuthLayout'
import { formatDate } from '../lib/format'
import type { PlatformTenant, PlatformTenantsResponse } from '../types/platform'

const today = new Date().toLocaleDateString('en-CA')
function statusLabel(status: PlatformTenant['status']) { return status === 'trial' ? '◷ Trial' : status === 'active' ? '✓ Active' : '× Expired' }

export default function PlatformDashboardPage() {
  const [tenants, setTenants] = useState<PlatformTenant[]>([]); const [pagination, setPagination] = useState<PlatformTenantsResponse['pagination']>({ page: 1, limit: 10, total: 0 }); const [loading, setLoading] = useState(true); const [notice, setNotice] = useState(''); const [paidTenant, setPaidTenant] = useState<PlatformTenant | null>(null); const [paidDate, setPaidDate] = useState(today); const [saving, setSaving] = useState(false); const [logoutLoading, setLogoutLoading] = useState(false)
  const load = useCallback((page = 1) => { setLoading(true); setNotice(''); platformApi.tenants<PlatformTenantsResponse>({ page, limit: pagination.limit }).then(({ data }) => { setTenants(data.tenants); setPagination(data.pagination) }).catch((error: ApiError) => { if (error.status === 401) window.location.assign('/platform/login'); else setNotice(error.message) }).finally(() => setLoading(false)) }, [pagination.limit])
  useEffect(() => { const timer = window.setTimeout(() => load(1), 0); return () => window.clearTimeout(timer) }, [load])
  const markPaid = async () => { if (!paidTenant) return; setSaving(true); setNotice(''); try { const { data } = await platformApi.markPaid(paidTenant.id, paidDate); setTenants((current) => current.map((tenant) => tenant.id === data.tenant.id ? data.tenant : tenant)); setPaidTenant(null) } catch (error) { setNotice((error as ApiError).status === 400 ? 'Choose a valid payment date.' : (error as ApiError).message) } finally { setSaving(false) } }
  const logout = async () => { setLogoutLoading(true); try { await platformApi.logout() } finally { window.location.assign('/platform/login') } }
  const pageCount = Math.max(1, Math.ceil(pagination.total / pagination.limit))
  return <main className="platform-shell"><header className="platform-header"><div><span className="eyebrow">Platform Admin</span><h1>Tenant network</h1><p>Every WarikaLk workspace, in one place.</p></div><button className="text-button" type="button" disabled={logoutLoading} onClick={logout}>{logoutLoading ? 'Signing out...' : 'Log out ↗'}</button></header><section className="platform-content"><div className="platform-summary"><span className="eyebrow">{pagination.total} tenants</span><span className="platform-session-label">Platform operations</span></div><ApiNotice message={notice} />{loading ? <div className="state-block"><Spinner /><p>Loading tenants...</p></div> : tenants.length === 0 ? <div className="state-block empty-state"><h2>No tenants yet.</h2><p>New workspaces will appear here.</p></div> : <><div className="platform-table-wrap"><table className="data-table platform-table"><thead><tr><th>Business</th><th>Owner</th><th>Status</th><th>Trial ends</th><th>Paid until</th><th>Created</th><th /></tr></thead><tbody>{tenants.map((tenant) => <tr key={tenant.id}><td><strong>{tenant.business_name}</strong></td><td>{tenant.owner_name}<small className="display-code">{tenant.owner_phone}</small></td><td><span className={`platform-status ${tenant.status}`}>{statusLabel(tenant.status)}</span></td><td>{formatDate(tenant.trial_ends_at)}</td><td>{tenant.paid_until ? formatDate(tenant.paid_until) : '—'}</td><td>{formatDate(tenant.created_at)}</td><td><button className="text-button mark-paid-button" type="button" onClick={() => { setPaidTenant(tenant); setPaidDate(today) }}>Mark as paid</button></td></tr>)}</tbody></table></div><div className="pagination"><span>Page {pagination.page} of {pageCount}</span><div><button className="text-button" disabled={pagination.page <= 1} onClick={() => load(pagination.page - 1)}>Previous</button> <button className="text-button" disabled={pagination.page >= pageCount} onClick={() => load(pagination.page + 1)}>Next</button></div></div></>}</section>{paidTenant && <div className="dialog-backdrop" role="presentation"><section className="dialog" role="dialog" aria-modal="true" aria-labelledby="paid-dialog-title"><p className="eyebrow">Subscription payment</p><h2 id="paid-dialog-title">Mark {paidTenant.business_name} as paid.</h2><p>Choose the date this tenant payment was received.</p><label className="field"><span>Paid date</span><input type="date" value={paidDate} onChange={(event) => setPaidDate(event.target.value)} /></label><div className="dialog-actions"><button className="secondary-button" type="button" onClick={() => setPaidTenant(null)} disabled={saving}>Cancel</button><button className="primary-button" type="button" onClick={markPaid} disabled={saving || !paidDate}>{saving ? <Spinner /> : 'Confirm payment'}<span>↗</span></button></div></section></div>}</main>
}