export type Language = 'en' | 'si'

export const translations = {
  en: {
    nav: { dashboard: 'Home', customers: 'Customers', loans: 'Loans', payments: 'Payments', monthlyReport: 'Monthly report', dailyReport: 'Daily report', staff: 'Staff', capitalLoss: 'Money lost', agentPerformance: 'Staff collections', logout: 'Log out', workspace: 'Workspace', ownerAccount: 'Owner account', staffAccount: 'Staff account' },
    common: { loading: 'Loading...', connectionFailed: 'Connection failed. Check your internet connection and try again.', customer: 'Customer', loan: 'Loan', paid: 'Paid', unpaid: 'Not paid', daily: 'Daily', monthly: 'Monthly', collect: 'Collect', markPaid: 'Mark as paid', yes: 'Yes', no: 'No', back: 'Back', today: 'Today', previous: 'Previous', next: 'Next', money: 'Money' },
    auth: { welcome: 'Welcome back', loginTitle: 'Keep the day moving.', loginIntro: 'Sign in to see what needs collecting, when it matters.', mobile: 'Mobile number', password: 'Password', code: 'One-time code', sendCode: 'Send code', login: 'Log in', loginWithCode: 'Sign in with code', forgot: 'Forgot password?', usePassword: 'Use password instead', codeLogin: 'Log in with a code', newTo: 'New to WarikaLk?', createAccount: 'Create an account', start: 'Start your workspace', signupTitle: 'Build a better collection day.', signupIntro: 'Set up your WarikaLk workspace in a few careful steps.', business: 'Business name', owner: 'Owner name', confirmPassword: 'Confirm password', verification: 'Verification code', createWorkspace: 'Create workspace', already: 'Already have an account?', change: 'Change' },
    reports: { monthlyTitle: 'Monthly report', monthlyIntro: 'See what you need to collect this month.', totalThisMonth: 'Total this month', collected: 'Collected', stillPending: 'Still pending', noMonthlyLoans: "No monthly loans yet. Add one from a customer's page.", dailyTitle: 'Daily report', dailyIntro: 'See who needs a visit and collect faster.', toCollect: 'to collect', collectedToday: 'collected', nothingDue: 'Nothing due on this date.', collectConfirm: 'Collect {amount} from {name}?', collectSuccess: 'Payment recorded.', chooseMonth: 'Choose month', chooseDate: 'Choose date', dueDate: 'Due date' },
  },
  si: {
    nav: { dashboard: 'මුල් පිටුව', customers: 'ගනුදෙනුකරුවන්', loans: 'ණය', payments: 'ගෙවීම්', monthlyReport: 'මාසික වාර්තාව', dailyReport: 'දිනපතා වාර්තාව', staff: 'කාර්ය මණ්ඩලය', capitalLoss: 'අහිමි වූ මුදල්', agentPerformance: 'කාර්ය මණ්ඩල එකතු කිරීම්', logout: 'ඉවත් වෙන්න', workspace: 'වැඩ අවකාශය', ownerAccount: 'අයිතිකරුගේ ගිණුම', staffAccount: 'කාර්ය මණ්ඩල ගිණුම' },
    common: { loading: 'පූරණය වෙමින්...', connectionFailed: 'සම්බන්ධ වුණේ නැහැ. අන්තර්ජාලය පරීක්ෂා කරලා නැවත උත්සාහ කරන්න.', customer: 'ගනුදෙනුකරු', loan: 'ණය', paid: 'ගෙවා ඇත', unpaid: 'ගෙවා නැත', daily: 'දිනපතා', monthly: 'මාසික', collect: 'මුදල් ගන්න', markPaid: 'ගෙවා ඇතැයි සලකන්න', yes: 'ඔව්', no: 'නැහැ', back: 'ආපසු', today: 'අද', previous: 'පෙර', next: 'ඊළඟ', money: 'මුදල්' },
    auth: { welcome: 'ආයුබෝවන්', loginTitle: 'වැඩේ ඉදිරියට ගෙනියමු.', loginIntro: 'අද එකතු කරන්න තියෙන මුදල් බලන්න ඇතුල් වෙන්න.', mobile: 'ජංගම දුරකථන අංකය', password: 'මුරපදය', code: 'OTP කේතය', sendCode: 'කේතය ගන්න', login: 'ඇතුල් වෙන්න', loginWithCode: 'කේතයෙන් ඇතුල් වෙන්න', forgot: 'මුරපදය අමතකද?', usePassword: 'මුරපදය භාවිතා කරන්න', codeLogin: 'කේතයෙන් ඇතුල් වෙන්න', newTo: 'WarikaLk අලුත්ද?', createAccount: 'ගිණුමක් හදන්න', start: 'වැඩ අවකාශය හදමු', signupTitle: 'එකතු කරන දවස ලේසි කරමු.', signupIntro: 'පියවර කිහිපයකින් WarikaLk වැඩ අවකාශය හදන්න.', business: 'ව්‍යාපාරයේ නම', owner: 'අයිතිකරුගේ නම', confirmPassword: 'මුරපදය නැවත ලියන්න', verification: 'තහවුරු කිරීමේ කේතය', createWorkspace: 'වැඩ අවකාශය හදන්න', already: 'දැනටමත් ගිණුමක් තියෙනවද?', change: 'වෙනස් කරන්න' },
    reports: { monthlyTitle: 'මාසික වාර්තාව', monthlyIntro: 'මේ මාසයේ එකතු කරන්න තියෙන මුදල් බලන්න.', totalThisMonth: 'මේ මාසයේ මුළු එකතුව', collected: 'එකතු කරලා', stillPending: 'තව ගන්න තියෙනවා', noMonthlyLoans: 'තාම මාසික ණය නැහැ. ගනුදෙනුකරුගේ පිටුවෙන් එකක් එකතු කරන්න.', dailyTitle: 'දිනපතා වාර්තාව', dailyIntro: 'අද යන්න ඕන තැන් බලලා ඉක්මනින් මුදල් ගන්න.', toCollect: 'ගන්න තියෙනවා', collectedToday: 'එකතු කරලා', nothingDue: 'මේ දවසට ගෙවන්න තියෙන මුදල් නැහැ.', collectConfirm: '{name} ගෙන් {amount} ගන්නද?', collectSuccess: 'ගෙවීම සටහන් කළා.', chooseMonth: 'මාසය තෝරන්න', chooseDate: 'දිනය තෝරන්න', dueDate: 'ගෙවිය යුතු දිනය' },
  },
} as const

export function translate(language: Language, key: string, values: Record<string, string | number> = {}) {
  let value: unknown = translations[language]
  for (const part of key.split('.')) value = (value as Record<string, unknown>)?.[part]
  if (typeof value !== 'string') return key
  return value.replace(/\{(\w+)\}/g, (_, name: string) => String(values[name] ?? `{${name}}`))
}